# Setup
title:               'Today I Learned'
tagline:             'Notes to self about software development'
description:         ''
url:                 'https://mbidasaria.github.io/'
baseurl:             'til/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Manish Bidasaria
  url:               https://twitter.com/GammaOverTheta
  email:             manish.bidasaria@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
